# Generated by Django 3.0.4 on 2020-08-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineersign', models.TextField()),
                ('managersign', models.TextField()),
                ('firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('STORE_NO', models.CharField(blank=True, max_length=30, null=True)),
                ('CALL_OUT_NO', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
