# Generated by Django 3.0.4 on 2020-08-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='engineersign',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='managersign',
            field=models.TextField(blank=True, null=True),
        ),
    ]
