# Generated by Django 3.0.4 on 2020-08-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200825_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineer',
            old_name='lastname',
            new_name='STORE',
        ),
    ]
